# Generated by Django 3.2.7 on 2021-10-09 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('pair', models.CharField(default='error', max_length=16)),
                ('type', models.CharField(default='BUYORSELL', max_length=16)),
                ('price', models.FloatField(default=0, max_length=20)),
                ('ammount', models.FloatField(default=0, max_length=20)),
                ('total', models.FloatField(default=0, max_length=20)),
                ('trade_fullfill', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
