# Generated by Django 3.2.7 on 2021-10-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_pendingtrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateXLSX',
        ),
    ]
