# Generated by Django 3.2.7 on 2021-10-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20211009_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hold',
            name='xlsx',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='xlsx',
        ),
        migrations.RemoveField(
            model_name='tradeonhold',
            name='xlsx',
        ),
    ]
