# Generated by Django 3.2.7 on 2021-10-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20211009_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hold',
            old_name='pair',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='pair',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='tradeonhold',
            old_name='pair',
            new_name='coin',
        ),
    ]
